from asyncio import create_task, Queue, Lock
from time import monotonic
from Backend.helper.task_manager import edit_message
from Backend.logger import LOGGER
from Backend import db
from Backend.helper.settings_manager import SettingsManager
from Backend.helper.pyro import clean_filename, get_readable_file_size, remove_urls
from Backend.helper.caption_tools import bold_caption, extract_supported_filename, preferred_caption_filename
from Backend.helper.metadata import metadata_from_caption_or_filename
from pyrogram import filters, Client, enums
from pyrogram.types import Message
from pyrogram.errors import FloodWait
from Backend.helper.metadata import extract_default_id
from Backend.helper.split_files import (
    detect_split_upload,
    strip_part_suffix,
    find_split_source,
    find_legacy_bare_split_source,
    resolve_legacy_bare_split_candidates,
    split_metadata_fields,
    is_video_filename,
)
from Backend.helper.subtitle_service import index_subtitle, relink_unmatched_subtitles
from Backend.helper.subtitle_constants import is_subtitle_file
from Backend.helper.upload_status import process_upload_statuses, queue_upload_status



file_queue = Queue()
db_lock = Lock()


# Ignore the edited-message event generated by our own automatic caption edit.
# The value stores (plain caption, expiry) so manual edits still re-index.
_AUTOCAPTION_GUARD: dict[tuple[int, int], tuple[str, float]] = {}
_AUTOCAPTION_GUARD_SECONDS = 45.0


def _message_file(message: Message):
    return message.video or message.document


def _caption_filename(message: Message) -> str:
    file = _message_file(message)
    return preferred_caption_filename(
        message.caption or "",
        getattr(file, "file_name", "") or "",
    )


def _utf16_length(value: str) -> int:
    return len(str(value or "").encode("utf-16-le")) // 2


def _caption_is_fully_bold(message: Message, plain_caption: str) -> bool:
    if (message.caption or "") != plain_caption:
        return False
    expected_length = _utf16_length(plain_caption)
    for entity in message.caption_entities or []:
        if (
            entity.type == enums.MessageEntityType.BOLD
            and int(entity.offset or 0) == 0
            and int(entity.length or 0) >= expected_length
        ):
            return True
    return False


def _cleanup_caption_guards() -> None:
    now = monotonic()
    for key, (_caption, expiry) in list(_AUTOCAPTION_GUARD.items()):
        if expiry <= now:
            _AUTOCAPTION_GUARD.pop(key, None)


def _is_automatic_caption_edit(message: Message) -> bool:
    _cleanup_caption_guards()
    key = (int(message.chat.id), int(message.id))
    guarded = _AUTOCAPTION_GUARD.get(key)
    if not guarded:
        return False
    expected, _expiry = guarded
    if (message.caption or "") == expected:
        _AUTOCAPTION_GUARD.pop(key, None)
        return True
    return False


async def _normalize_supported_caption(message: Message) -> None:
    filename = _caption_filename(message)
    if not filename or _caption_is_fully_bold(message, filename):
        return
    _cleanup_caption_guards()
    key = (int(message.chat.id), int(message.id))
    _AUTOCAPTION_GUARD[key] = (filename, monotonic() + _AUTOCAPTION_GUARD_SECONDS)
    await edit_message(
        chat_id=message.chat.id,
        msg_id=message.id,
        new_caption=bold_caption(filename),
    )


def _schedule_caption_normalization(message: Message) -> None:
    create_task(_normalize_supported_caption(message))


def _split_source_info(message: Message):
    """Return the canonical source name + split info for a channel upload."""
    file = message.video or message.document
    filename = getattr(file, "file_name", "") or ""
    caption_filename = extract_supported_filename(message.caption or "")
    source, info = find_split_source(
        caption_filename,
        filename,
        clean_filename(caption_filename),
        clean_filename(filename),
    )
    if info:
        return source, info
    # MIME-aware fallback for Telegram clients which expose a ZIP part as
    # `movie.mkv.001` or append invisible characters to its document name.
    info = detect_split_upload(filename, getattr(file, "mime_type", "") or "")
    if info:
        return filename, info
    return None, None


def _split_source_name(message: Message) -> str | None:
    source, _ = _split_source_info(message)
    return source


# A normal live upload is handled one message at a time.  Legacy raw volumes
# named `Movie.001.mkv` cannot be trusted from the filename alone, so look only
# at recently posted sibling media before promoting the current upload.  The
# scanner uses the same validation rule across its batches.
_LEGACY_SPLIT_LIVE_LOOKBACK = 200


def _legacy_bare_split_candidate(message: Message):
    file = message.video or message.document
    if file is None:
        return None
    message_id = int(getattr(message, "id", 0) or 0)
    if message_id <= 0:
        return None
    filename = getattr(file, "file_name", "") or ""
    caption = extract_supported_filename(message.caption or "")
    source, info = find_legacy_bare_split_source(
        caption,
        filename,
        clean_filename(caption),
        clean_filename(filename),
    )
    return (message_id, source, info) if source and info else None


async def _contextual_legacy_split_for_live_upload(client: Client, message: Message):
    """Return split metadata for the current legacy `.001.mkv` upload.

    A new `.001` remains normal until a matching `.002` exists.  When `.002`
    arrives, the preceding `.001` is found from the channel history and the
    database converts that indexed normal row into a virtual-stream part.
    This never accepts `.720.mkv`, `.1.mkv`, or any non-zero-padded suffix.
    """
    current = _legacy_bare_split_candidate(message)
    if not current:
        return None, None

    message_id, source, _info = current
    start = max(1, message_id - _LEGACY_SPLIT_LIVE_LOOKBACK)
    candidates = []
    try:
        history = await client.get_messages(message.chat.id, list(range(start, message_id + 1)))
        if not isinstance(history, list):
            history = [history]
        for sibling in history:
            if sibling is None or getattr(sibling, "empty", False):
                continue
            candidate = _legacy_bare_split_candidate(sibling)
            if candidate:
                candidates.append((candidate[0], candidate[2]))
    except FloodWait as exc:
        LOGGER.info("[LegacySplit] Live context postponed by FloodWait %ss.", exc.value)
        return None, None
    except Exception as exc:
        LOGGER.debug("[LegacySplit] Live context unavailable for msg %s: %s", message_id, exc)
        return None, None

    accepted = resolve_legacy_bare_split_candidates(candidates)
    info = accepted.get(message_id)
    if not info:
        return None, None
    LOGGER.info(
        "[LegacySplit] Live upload msg %s accepted after consecutive sibling validation.",
        message_id,
    )
    return source, info


def _is_supported_media(message: Message) -> bool:
    if message.video:
        return True
    if message.document:
        filename = message.document.file_name or ""
        caption = extract_supported_filename(message.caption or "")
        mime_type = (message.document.mime_type or "").lower()
        if mime_type.startswith("video/"):
            return True
        # Captions are deliberately checked before document names. This also
        # supports clients that upload normal video files as octet-stream.
        if is_video_filename(caption) or is_video_filename(filename):
            return True
        # `.mkv.zip.001` volumes normally arrive as application/zip or octet-stream.
        return _split_source_info(message)[1] is not None
    return False


def _is_subtitle_message(message: Message) -> bool:
    if not message.document or message.video:
        return False
    mime_type = message.document.mime_type or ""
    # Caption first, then filename fallback. MIME type remains authoritative
    # for subtitle documents whose captions omit the extension.
    caption_filename = extract_supported_filename(message.caption or "")
    return is_subtitle_file(caption_filename, mime_type) or is_subtitle_file(
        message.document.file_name or "",
        mime_type,
    )


def _upload_display_name(message: Message) -> str:
    """Return the original Telegram filename for upload status replies."""
    file = message.video or message.document
    return (getattr(file, "file_name", "") or "Unknown file").strip()


def _media_status_context(
    *,
    client: Client,
    message: Message,
    metadata_info: dict,
    fallback_title: str,
    size: str,
    action: str,
) -> dict:
    """Build the compact status only after metadata has been resolved."""
    del fallback_title, size
    return {
        "client": client,
        "chat_id": int(message.chat.id),
        "reply_to_message_id": int(message.id),
        "kind": "SPLIT" if metadata_info.get("group_key") else "VIDEO",
        "title": _upload_display_name(message),
        "detail": "",
        "action": action,
    }


async def _notify_upload_failure(
    client: Client,
    message: Message,
    *,
    kind: str,
    action: str,
    detail: str = "",
) -> None:
    await queue_upload_status(
        client=client,
        chat_id=int(message.chat.id),
        reply_to_message_id=int(message.id),
        kind=kind,
        state="failed",
        action=action,
        title=_upload_display_name(message),
        detail=detail,
    )


async def _index_subtitle_message(client: Client, message: Message, *, action: str) -> None:
    document = message.document
    channel = int(str(message.chat.id).replace("-100", ""))
    try:
        record = await index_subtitle(
            db,
            channel=channel,
            msg_id=message.id,
            filename=document.file_name or message.caption or "subtitle.srt",
            caption=message.caption or "",
            raw_size=document.file_size or 0,
            size=get_readable_file_size(document.file_size or 0),
            mime_type=document.mime_type or "",
        )
    except Exception as exc:
        LOGGER.error("Subtitle indexing failed for message %s: %s", message.id, exc, exc_info=True)
        await _notify_upload_failure(
            client,
            message,
            kind="SUBTITLE",
            action="Index failed",
        )
        return

    status = str(record.get("status") or "unmatched").lower()
    await queue_upload_status(
        client=client,
        chat_id=int(message.chat.id),
        reply_to_message_id=int(message.id),
        kind="SUBTITLE",
        state="success" if status == "matched" else "warning",
        action=action if status == "matched" else "Indexed · Match pending",
        title=_upload_display_name(message),
    )


async def _queue_media_index(
    client: Client,
    message: Message,
    *,
    action: str,
    override_id: str | None = None,
) -> bool:
    """Resolve metadata and queue media work; delivery status follows DB completion."""
    file = message.video or message.document
    title = _upload_display_name(message)
    split_source, split_upload_info = _split_source_info(message)
    legacy_candidate = _legacy_bare_split_candidate(message)
    if not split_upload_info:
        split_source, split_upload_info = await _contextual_legacy_split_for_live_upload(client, message)

    metadata_source = split_source or title
    msg_id = int(message.id)
    raw_size = int(file.file_size or 0)
    size = get_readable_file_size(raw_size)
    channel = int(str(message.chat.id).replace("-100", ""))
    metadata_info = await metadata_from_caption_or_filename(
        caption=message.caption or "",
        filename=metadata_source,
        channel=channel,
        msg_id=msg_id,
        override_id=override_id,
        split_info_override=split_upload_info,
    )

    status_kind = "SPLIT" if split_upload_info else "VIDEO"
    # Persist the original Telegram caption and file name. Custom catalog tag
    # rules use these values without changing the file shown to stream users.
    if metadata_info is not None:
        metadata_info["source_caption"] = message.caption or ""
        metadata_info["source_filename"] = getattr(file, "file_name", "") or title

    if metadata_info is None:
        LOGGER.warning("Metadata failed for file: %s (ID: %s)", title, msg_id)
        await _notify_upload_failure(
            client,
            message,
            kind=status_kind,
            action="Metadata not found",
            detail=size,
        )
        return False

    if legacy_candidate and not split_upload_info:
        metadata_info["legacy_source_filename"] = legacy_candidate[1]

    title = remove_urls(metadata_source if metadata_info.get("group_key") else title)
    if not metadata_info.get("group_key"):
        recovered_split = split_upload_info or find_split_source(
            extract_supported_filename(message.caption or ""),
            title,
            metadata_source,
        )[1]
        if recovered_split:
            metadata_info.update(
                split_metadata_fields(channel, metadata_info.get("quality"), recovered_split)
            )
            LOGGER.info(
                "[SplitRecovery] live msg %s: %s → part %s",
                msg_id,
                title,
                recovered_split.part_number,
            )

    if metadata_info.get("group_key"):
        title = metadata_info.get("media_filename") or strip_part_suffix(title)
    if not title.lower().endswith((
        ".mkv", ".mp4", ".avi", ".ts", ".m4v", ".mov", ".wmv", ".webm",
        ".flv", ".mpeg", ".mpg",
    )):
        title += ".mkv"

    status_context = _media_status_context(
        client=client,
        message=message,
        metadata_info=metadata_info,
        fallback_title=title,
        size=size,
        action=action,
    )
    await file_queue.put(
        (metadata_info, channel, msg_id, size, raw_size, title, status_context)
    )
    return True


async def process_file():
    while True:
        (
            metadata_info,
            channel,
            msg_id,
            size,
            raw_size,
            title,
            status_context,
        ) = await file_queue.get()
        try:
            async with db_lock:
                updated_id = await db.insert_media(
                    metadata_info,
                    channel=channel,
                    msg_id=msg_id,
                    size=size,
                    raw_size=raw_size,
                    name=title,
                )

            if updated_id:
                try:
                    from Backend.helper.tag_catalog import sync_tag_catalog_for_identity
                    await sync_tag_catalog_for_identity(
                        db, metadata_info.get("media_type", "movie"), metadata_info.get("tmdb_id")
                    )
                except Exception as exc:
                    LOGGER.debug("Tag catalog refresh skipped for live message %s: %s", msg_id, exc)
                try:
                    await relink_unmatched_subtitles(db, limit=150)
                except Exception as exc:
                    LOGGER.warning("Subtitle relink after message %s failed: %s", msg_id, exc)

                await queue_upload_status(
                    client=status_context["client"],
                    chat_id=status_context["chat_id"],
                    reply_to_message_id=status_context["reply_to_message_id"],
                    kind=status_context["kind"],
                    state="success",
                    action=status_context["action"],
                    title=status_context["title"],
                    detail=status_context["detail"],
                )
            else:
                LOGGER.warning("Media update failed due to validation errors for message %s.", msg_id)
                await queue_upload_status(
                    client=status_context["client"],
                    chat_id=status_context["chat_id"],
                    reply_to_message_id=status_context["reply_to_message_id"],
                    kind=status_context["kind"],
                    state="failed",
                    action="Index failed",
                    title=status_context["title"],
                    detail="Validation rejected",
                )
        except Exception as exc:
            LOGGER.error("Media indexing failed for message %s: %s", msg_id, exc, exc_info=True)
            await queue_upload_status(
                client=status_context["client"],
                chat_id=status_context["chat_id"],
                reply_to_message_id=status_context["reply_to_message_id"],
                kind=status_context["kind"],
                state="failed",
                action="Index failed",
                title=status_context["title"],
                detail="Database error",
            )
        finally:
            file_queue.task_done()


create_task(process_file())
create_task(process_upload_statuses())


@Client.on_message(filters.channel & (filters.document | filters.video))
async def file_receive_handler(client: Client, message: Message):
    if str(message.chat.id) not in SettingsManager.current().auth_channels:
        return

    try:
        if _is_subtitle_message(message):
            _schedule_caption_normalization(message)
            await _index_subtitle_message(client, message, action="Indexed")
            return

        if _is_supported_media(message):
            _schedule_caption_normalization(message)
            await _queue_media_index(client, message, action="Indexed")
            return

        file = message.video or message.document
        await queue_upload_status(
            client=client,
            chat_id=int(message.chat.id),
            reply_to_message_id=int(message.id),
            kind="FILE",
            state="skipped",
            action="Unsupported file",
            title=_upload_display_name(message),
        )
    except FloodWait as exc:
        LOGGER.warning("Live upload handling hit FloodWait for message %s: %ss", message.id, exc.value)
        await _notify_upload_failure(
            client,
            message,
            kind="FILE",
            action="Rate limited",
            detail=f"Retry in {exc.value}s",
        )
    except Exception as exc:
        LOGGER.error("Error handling generic file %s: %s", message.id, exc, exc_info=True)
        await _notify_upload_failure(
            client,
            message,
            kind="FILE",
            action="Processing error",
        )


@Client.on_edited_message(filters.channel & (filters.document | filters.video))
async def file_edited_handler(client: Client, message: Message):
    if str(message.chat.id) not in SettingsManager.current().auth_channels:
        return
    if _is_automatic_caption_edit(message):
        return

    try:
        if _is_subtitle_message(message):
            await _index_subtitle_message(client, message, action="Updated")
            _schedule_caption_normalization(message)
            return

        if not _is_supported_media(message):
            return

        # Caption edits can repair a title even without an IMDb/TMDb ID.
        # Re-run the same caption-first → filename-fallback resolver for every
        # supported media edit; an explicit ID remains an optional override.
        override_id = extract_default_id(message.caption) if message.caption else None

        channel = int(str(message.chat.id).replace("-100", ""))
        await db.remove_media_part(channel, int(message.id))
        await _queue_media_index(
            client,
            message,
            action="Updated",
            override_id=override_id,
        )
        _schedule_caption_normalization(message)
    except FloodWait as exc:
        LOGGER.warning("Edited upload handling hit FloodWait for message %s: %ss", message.id, exc.value)
        await _notify_upload_failure(
            client,
            message,
            kind="FILE",
            action="Rate limited",
            detail=f"Retry in {exc.value}s",
        )
    except Exception as exc:
        LOGGER.error("Error handling edited generic file %s: %s", message.id, exc, exc_info=True)
        await _notify_upload_failure(
            client,
            message,
            kind="FILE",
            action="Update failed",
        )


@Client.on_deleted_messages(filters.channel)
async def file_deleted_handler(client: Client, messages: list[Message]):
    try:
        
        for message in messages:
            if message.chat and str(message.chat.id) in SettingsManager.current().auth_channels:
                channel = str(message.chat.id).replace("-100", "")
                msg_id = message.id
                
                try:
                    deleted = await db.remove_media_part(int(channel), msg_id)
                    subtitle_deleted = await db.delete_subtitle_by_message(int(channel), msg_id)
                    
                    if deleted or subtitle_deleted:
                        LOGGER.info(f"Automatically purged deleted message {msg_id} from database.")
                except Exception as ex:
                    LOGGER.error(f"Failed to scrub deleted message {msg_id}: {ex}")
                    
    except Exception as e:
        LOGGER.error(f"Error handling deleted messages: {e}")
